[build-system]
  requires = ["hatchling"]
  build-backend = "hatchling.build"

[project]
  name = "diffsptk"
  authors = [
    {name = "SPTK Working Group"}
  ]
  maintainers = [
    {name = "Takenori Yoshimura", email="takenori@sp.nitech.ac.jp"}
  ]
  description = "Speech signal processing modules for machine learning"
  readme = "README.md"
  requires-python = ">=3.8"
  keywords = [
    "ddsp",
    "dsp",
    "pytorch",
    "signal processing",
    "sptk",
  ]
  license = {text = "Apache 2.0"}
  classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
  ]
  dependencies = [
    "soundfile",
    "torch >= 1.10.0",
    "torchcrepe >= 0.0.16",
    "numpy",
    "vector-quantize-pytorch >= 0.8.0",
  ]
  dynamic = ["version"]

[project.optional-dependencies]
  dev = [
    "black",
    "build",
    "isort",
    "numpydoc",
    "pydata-sphinx-theme",
    "pyproject-flake8",
    "pytest",
    "pytest-cov",
    "sphinx",
    "twine",
  ]

[project.urls]
  Homepage = "https://sp-tk.sourceforge.net/"
  Documentation = "https://sp-nitech.github.io/diffsptk/latest/"
  Source = "https://github.com/sp-nitech/diffsptk"

[tool.hatch.build]
  exclude = ["assets", "docs", "tests", "tools"]

[tool.hatch.version]
  path = "diffsptk/version.py"

[tool.flake8]
  max-line-length = 88
  extend-ignore = ["E203"]
  exclude = ["__init__.py"]

[tool.isort]
  force_single_line = true
  force_sort_within_sections = true
  include_trailing_comma = true
  multi_line_output = 3
  sort_order = "native"
  use_parentheses = true

[tool.coverage.report]
  exclude_lines = [
    "pragma: no cover",
    "raise RuntimeError",
    "raise ValueError",
    "verbose",
    "warn_type",
    "warnings",
  ]

[tool.coverage.run]
  disable_warnings = [
    "couldnt-parse",
  ]

[tool.pytest.ini_options]
  filterwarnings = [
    "ignore:Casting complex values to real discards the imaginary part",
  ]
